defmodule BadgeGeneratorApi.Repo.Migrations.AddCompanyAndApiKey do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:company_api_keys, primary_key: false) do
      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :extra_data, :map
      add :purpose, :text, null: false
      add :expires_at, :utc_datetime, null: false
      add :subject, :text, null: false
      add :jti, :text, null: false, primary_key: true
      add :company_id, :uuid
    end

    create table(:companies, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:company_api_keys) do
      modify :company_id,
             references(:companies,
               column: :id,
               name: "company_api_keys_company_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:companies) do
      add :name, :text, null: false
      add :email, :text, null: false
    end
  end

  def down do
    alter table(:companies) do
      remove :email
      remove :name
    end

    drop constraint(:company_api_keys, "company_api_keys_company_id_fkey")

    alter table(:company_api_keys) do
      modify :company_id, :uuid
    end

    drop table(:companies)

    drop table(:company_api_keys)
  end
end
