defmodule BadgeGeneratorApi.Repo.Migrations.AddApiKeyFixes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint("company_api_keys", "company_api_keys_pkey")

    alter table(:company_api_keys) do
      remove :jti
      remove :subject
      remove :purpose
      remove :extra_data
      remove :created_at
      remove :updated_at
      modify :expires_at, :utc_datetime, null: true
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :api_key, :text, null: false
    end
  end

  def down do
    drop constraint("company_api_keys", "company_api_keys_pkey")

    alter table(:company_api_keys) do
      remove :api_key
      remove :id
      modify :expires_at, :utc_datetime, null: false

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :extra_data, :map
      add :purpose, :text, null: false
      add :subject, :text, null: false
      add :jti, :text, null: false, primary_key: true
    end
  end
end
