defmodule BadgeGeneratorApi.Repo.Migrations.CreateAchievementQuests do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:achievement_quests, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text, null: false
      add :description, :text
      add :badge_img_url, :text
      add :criteria_category, :text, null: false
      add :criteria_details, :map, null: false
      add :start_at, :utc_datetime
      add :end_at, :utc_datetime
      add :is_active, :boolean, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :project_id,
          references(:projects,
            column: :id,
            name: "achievement_quests_project_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:achievement_quests, "achievement_quests_project_id_fkey")

    drop table(:achievement_quests)
  end
end
