defmodule BadgeGeneratorApi.Repo.Migrations.UpdateBusinessTable do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:businesses) do
      remove :password
      remove :password_hash
    end

    alter table(:business_api_keys) do
      modify :expired_at, :utc_datetime, null: false
    end
  end

  def down do
    alter table(:business_api_keys) do
      modify :expired_at, :utc_datetime, null: true
    end

    alter table(:businesses) do
      add :password_hash, :text
      add :password, :text, null: false
    end
  end
end
